LABORATORIO 2
JORGE ALONZO



```{r}
library(nycflights13)
View(flights)
View(airports)
View(planes)
View(airlines)
View(weather)
library(tidyverse)
library(dplyr)
library(ggplot2)
```



1. Inner-join
1.1
```{r}
flights%>%
  inner_join(planes,by="tailnum")

```
1.2

```{r}
flights%>%
    inner_join(airlines,by="carrier")


```
 1.3
 
```{r}

flights%>%
  inner_join(airports, c("dest" = "faa"))%>%
  inner_join(airports, c("origin" = "faa"))


```
 
1.4

```{r}
flights%>%
  inner_join(weather,by=c("year", "month", "day", "hour","origin"))
```

2. Data manipulation
2.1
```{r}
flights%>%
  count(year,month,day)%>%
  filter(n>1000)%>%
  arrange(n)
```
2.2

```{r}
flights_selected=flights%>%
  select(year:day,hour, origin, dest, tailnum,carrier, arr_delay, dep_delay)

flights_selected
```

2.3

```{r}
flights_selected%>%
  left_join(airlines)%>%
  select(-origin,-dest)%>%
  mutate(tot_delay=arr_delay+dep_delay)


```

2.4

```{r}
precip_delay=flights%>%
  inner_join(weather,by=c("year", "month", "day", "hour","origin"))%>%
  group_by(precip)%>%
  summarize(delay=mean(dep_delay,na.rm=TRUE))%>%
  replace_na()

precip_delay
  
```

2.5
```{r}
ggplot(precip_delay,aes(x=precip,y=delay))+
  geom_point()

```
2.6

```{r}
flights_airports=flights%>%
  filter(year==2013, month==5, day==10)%>%
  group_by(dest)%>%
  summarize(delay=mean(arr_delay,na.rm=TRUE))%>%
  inner_join(airports,by=character())

flights_airports
```

2.7
```{r}
ggplot(flights_airports, aes(x=lon, y=lat,color=delay))+geom_point()


```









